(function () {
    'use strict';

    angular.module(APPNAME)
        .component('editHours', {
            templateUrl: '../Scripts/components/edit-hours/_main.html',
            controller: 'hoursController'
        });

    angular.module(APPNAME)
        .controller('hoursController', hoursController);

    hoursController.$inject = ['hoursService'];

    function hoursController(hoursService) {
        var vm = this;


        // form is Pascal Case because the Angular view model must match the .NET request model 
        // an 'hours' entry looks like this:
        vm.form = {
            Id: null, // autogenerated by server
            Week: null,
            Date: null,
            TotalHoursWorked: null,
            DirectClientContact: null,
            IndirectClientHours: null,
            SupervisionHours: null,
            ExplanationOfSce: null
        };
        vm.hoursArray = [];
        vm.editMode = false;
        vm.getAllEntries = _getAllEntries;
        vm.createEntry = _createEntry;
        vm.editEntry = _editEntry;
        vm.clearForm = _clearForm;
        vm.deleteEntry = _deleteEntry;
        vm.updateEntry = _updateEntry;
        vm.$onInit = _getAllEntries();


        function _getAllEntries() {
            hoursService.getAllEntries()
                .then(response => vm.hoursArray = response.data, error => console.error(error));
        }

        function _createEntry() {
            console.log('vm.form', vm.form);
            hoursService.createEntry(vm.form)
                .then(_success, error => console.error(error));

            function _success(response) {
                _getAllEntries();
                console.log(response);
            }
        }

        function _editEntry(entry) { 
            vm.form = angular.copy(entry);
            vm.editMode = true;
        }

        function _clearForm() {
            vm.form = null;
            vm.editMode = false;
        }

        function _deleteEntry(id, $event) {
            $event.stopPropagation();
            hoursService.deleteEntry(id)
                .then(_complete, error => console.error(error));

            function _complete(response) {
                _getAllEntries();
                console.log(response);
            }
        }

        function _updateEntry() {
            hoursService.updateEntry(vm.form)
                .then(_success, _error);
        }
    }
})();